require 'pry'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

# Examples:

#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# vicente = User.create({user_name: "vinny_gums", email: "vicente@aol.com"})

# spider_man = Game.create({name: "Marvel's Spider-Man", developer: "Insomniac", genre:"Action-Adventure", description:"With great power...you know the rest. Enjoy playing as Spider-Man in modern day New York City"})
# the_last_of_us = Game.create({name: "The Last of Us", developer: "Naughty Dog", genre:"Action-Adventure, Survival-Horror", description:"Control Joel, a smuggler tasked with escorting a teenage girl, Ellie, across a post-apocalyptic United States."})
# jet_set_radio_future = Game.create({name: "Jet Set Radio Future", developer: "Smilebit", genre:"Action Sports", description:"A game where a player controls a member of a gang of inline skaters called the GGs to gain control of a futuristic Tokyo"})
# def_jam_fight_for_ny = Game.create({name: "Def Jam Fight For NY", developer: "EA", genre:"Fighting", description:"Got a score to settle with Snoop, Busta Rhymes, or any other artist from the early 2000's? Pick up the sticks."})
# skate_3 = Game.create({name: "Skate 3", developer: "EA", genre:"Extreme Sport", description:"Skate around and fall in love."})






# PS4 Games
god_of_war = Game.create({name: "God of War", developer: "SIE Santa Monica Studio", genre: "Action-adventure", description: "God of War is an action-adventure video game developed by Santa Monica Studio and published by Sony Interactive Entertainment (SIE). Released on April 20, 2018, for the PlayStation 4 (PS4) console, it is the eighth installment in the God of War series, the eighth chronologically, and the sequel to 2010's God of War III.", picture_url: "https://cdn.images.dailystar.co.uk/dynamic/184/photos/687000/620x/God-of-War-PS4-REVIEW-Best-2018-release-to-date-may-also-be-the-Game-of-the-Generation-696197.jpg",release_date: "April 20, 2018", system: "PS4", video: "https://www.youtube.com/embed/K0u_kAWLJOA"})

marvels_spiderman_game = Game.create({name: "Marvel's Spider-Man", developer: "Insomniac Games", genre: "Action-adventure", description: "Marvel's Spider-Man is an action-adventure game developed by Insomniac Games and published by Sony Interactive Entertainment for the PlayStation 4, based on the Marvel Comics superhero Spider-Man.", picture_url: "https://cdn.wccftech.com/wp-content/uploads/2018/04/Spider-Man_PS4_Crouch.jpg", release_date: "September 7, 2018", system: "PS4", video:"https://www.youtube.com/embed/q4GdJVvdxss"})

arkham_knight = Game.create({name: "Arkham Knight", developer: "Rocksteady Studios", genre: "Action-adventure", description: "Batman: Arkham Knight is a 2015 action-adventure video game developed by Rocksteady Studios and published by Warner Bros. Interactive Entertainment. Based on the DC Comics superhero Batman, it is the successor to the 2013 video game Batman: Arkham Origins, and the fourth main installment in the Batman: Arkham series. Written by Sefton Hill, Ian Ball and Martin Lancaster, Arkham Knight is inspired by the long-running comic book mythos. Set one year after the events of 2011's Batman: Arkham City, the game's main storyline follows Batman as he confronts Scarecrow, who has launched an attack on Gotham City, causing a citywide evacuation. Scarecrow, with the help of the mysterious Arkham Knight, is also able to unite Batman's greatest foes in an attempt to finally destroy Batman", picture_url: "https://en.wikipedia.org/wiki/File:Batman_Arkham_Knight_Cover_Art.jpg", release_date: "June 23, 2015", system: "PS4", video:"https://www.youtube.com/embed/wsf78BS9VE0"})

uncharted_4 = Game.create({name: "Uncharted 4: A Thief's End", developer: "Naughty Dog", genre: "Action-adventure", description: "Uncharted 4: A Thief's End is an action-adventure game developed by Naughty Dog and published by Sony Computer Entertainment for PlayStation 4 in May 2016. Following Uncharted 3: Drake's Deception, it is the final Uncharted game to feature protagonist Nathan Drake (portrayed by Nolan North). Drake, retired from fortune hunting with his wife Elena, reunites with his estranged older brother Sam and longtime partner Sully to search for Captain Henry Avery's lost treasure", picture_url: "https://en.wikipedia.org/wiki/File:Uncharted_4_box_artwork.jpg", release_date: "May 10, 2016", system: "PS4", video: "https://www.youtube.com/embed/hh5HV4iic1Y"})

the_last_of_us = Game.create({name: "The Last of Us", developer: "Naughty Dog", genre: "Action-adventure, Survival-Horror", description: "The Last of Us is an action-adventure survival horror video game developed by Naughty Dog and published by Sony Computer Entertainment. It was released for the PlayStation 3 worldwide on June 14, 2013. Players control Joel, a smuggler tasked with escorting a teenage girl, Ellie, across a post-apocalyptic United States. The Last of Us is played from a third-person perspective; players use firearms and improvised weapons, and can use stealth to defend against hostile humans and cannibalistic creatures infected by a mutated strain of the Cordyceps fungus. In the game's online multiplayer mode, up to eight players engage in cooperative and competitive gameplay", picture_url: "https://en.wikipedia.org/wiki/File:Video_Game_Cover_-_The_Last_of_Us.jpg", release_date: "June 14, 2013", system: "PS4", video: "https://www.youtube.com/embed/OQWD5W3fpPM"})

bloodborne = Game.create({name: "Bloodborne", developer: "FromSoftware", genre: "Action role-playing", description: "Bloodborne[a] is an action role-playing game developed by FromSoftware and published by Sony Computer Entertainment for PlayStation 4. Announced at Sony's E3 2014 conference, the game was released worldwide in March 2015. Bloodborne follows the player character, the Hunter, through the decrepit Gothic, Victorian era-inspired city of Yharnam, whose inhabitants have been afflicted with an abnormal blood-borne disease, with the player character unraveling the city's intriguing mysteries while fighting beasts, ultimately attempting to find the source of the plague and stop it.", picture_url: "https://en.wikipedia.org/wiki/File:Bloodborne_Cover_Wallpaper.jpg", release_date: "March 24, 2015 ", system: "PS4", video: "https://www.youtube.com/embed/G203e1HhixY"})

horizon_zero_dawn = Game.create({name: "Horizon Zero Dawn", developer: "Guerrilla Games", genre: "Action role-playing", description: "Horizon Zero Dawn is an action role-playing video game developed by Guerrilla Games and published by Sony Interactive Entertainment. It was released for the PlayStation 4 in early 2017. The plot follows Aloy, a hunter in a world overrun by machines, who sets out to uncover her past. The player uses ranged weapons, a spear and stealth to combat mechanised creatures and loot their remains. A skill tree provides the player with new abilities and bonuses. The player can explore the open world to discover side quests.", picture_url: "https://en.wikipedia.org/wiki/File:Horizon_Zero_Dawn.jpg", release_date: "February 28, 2017", system: "PS4", video:"https://www.youtube.com/embed/Fkg5UVTsKCE"})

hitman_2 = Game.create({name: "Hitman 2", developer: "IO Interactive", genre: "Stealth", description: "Following the events of Hitman, Agent 47 embarks on a mission to hunt the mysterious Shadow Client and disassemble his militia. His first lead is the location of one of the Shadow Client's lieutenants, Alma Reynard. 47 is able to gain some intel on the Shadow Client's activities from Reynard's home in New Zealand before eliminating her. Impressed with 47's performance, Providence authorizes him and the ICA to hunt down the rest of the Shadow Client's militia. When 47 asks Diana why the ICA would be willing to work with Providence, she replies that both organizations share interests in putting a stop to the Shadow Client, whose activities are now causing a global panic. She also reveals that Providence secretly promised to her to reveal 47's past.", picture_url: "https://en.wikipedia.org/wiki/File:Hitman_2_(2018)_cover.jpg", release_date: "November 13,2018", system: "PS4", video: "https://www.youtube.com/embed/onEO0pcnLDU"})

# //Switch
super_smash_bros = Game.create({name: "Super Smash Bros Ultimate", developer: "Bandai Namco Studios Sora Ltd.", genre: "Fighting", description: "Super Smash Bros. Ultimate[a] is an upcoming crossover fighting game developed by Bandai Namco Studios and Sora Ltd. and published by Nintendo for the Nintendo Switch. It is the fifth installment in the Super Smash Bros. series, succeeding Super Smash Bros. for Nintendo 3DS and Wii U. The game follows the series' traditional style of gameplay: controlling one of various characters, players must use differing attacks to weaken their opponents and knock them out of an arena. It features a wide variety of game modes, including a campaign for a single-player and multiplayer versus modes.", picture_url: "https://en.wikipedia.org/wiki/File:Super_Smash_Bros._Ultimate.jpg", release_date: "December 7,2018", system: "Nintendo Switch", video: "https://www.youtube.com/embed/TUzZKLirkrE"})

super_mario_odyssey = Game.create({name: "Super Mario Odyssey", developer: "Nintendo EPD", genre: "Action-Adventure", description: "Super Mario Odyssey[a] is a platform game published by Nintendo for the Nintendo Switch on October 27, 2017. An entry in the Super Mario series, it follows Mario and Cappy, a spirit that turns into Mario's hat and allows him to possess other characters and objects, as they journey across various worlds to save Princess Peach from his nemesis Bowser, who plans to forcibly marry her. In contrast to the linear gameplay of prior entries, the game returns to the primarily open-ended, exploration-based gameplay featured in Super Mario 64 and Super Mario Sunshine", picture_url: "https://en.wikipedia.org/wiki/File:Super_Mario_Odyssey.jpg", release_date: "October 27, 2017", system: "Nintendo Switch", video: "https://www.youtube.com/embed/wGQHQc_3ycE"})

octopath_traveler = Game.create({name: "Octopath Traveler", developer: "Square Enix", genre: "Role-Playing", description: "Choose your fate. Eight stories await.Eight travelers. Eight adventures. Eight roles to play in a new world brought to life by Square Enix. And now, you can enjoy all of them in the new demo. Step into the shoes and live the stories of each of the eight travelers and freely explore the world of Orsterra. Then, carry your choices and adventure into the main game with save data transfer.Use each character’s special abilities in and out of battle. Break through enemy defenses by discovering and targeting weaknesses. Store Boost Points with each turn and then spend them at strategic times to strengthen abilities, chain attacks, or provide aid. Choose the path you wish to walk and discover what lies beyond the horizon.", picture_url: "https://en.wikipedia.org/wiki/File:Octopath_Traveler.jpg", release_date: "July 13,2018", system: "Nintendo Switch", video: "https://www.youtube.com/embed/Z0nm7gXX0Vs"})

xenoblade_chronicles_2 = Game.create({name: "Xenoblade Chronicles 2", developer: "Monolith Soft", genre: "Action role-playing", description: "Xenoblade Chronicles 2[a] is an action role-playing game developed by Monolith Soft and published by Nintendo for the Nintendo Switch video game console. The game is part of the Xeno series, serving as a sequel to the first Xenoblade Chronicles, and was released worldwide on December 1, 2017. The game sold over a million copies within a month of its release. A large story-based downloadable content (DLC) addition, titled Xenoblade Chronicles 2: Torna – The Golden Country, was released in September 2018", picture_url: "https://en.wikipedia.org/wiki/File:Xenoblade_Chronicles_2_Boxart.jpg", release_date: "December 1,2017", system: "Nintendo Switch", video: "https://www.youtube.com/embed/xksPVZptPGM"})

dead_cells = Game.create({name: "Dead Cells", developer: "Motion Twin", genre: "Roguelike, metoidvania", description: "In the game, the player takes the role of a body of cells that take control of a corpse in a dungeon, through which they must fight their way out. The player gains various weapons, treasure and other tools through exploration of the procedurally-generated levels to fight undead creatures within it. At times, the player may gain cells, a type of in-game currency that can be used to purchase permanent upgrades for the player if they reach a vendor near the end of each level. If they fail to reach this vendor before dying, they lose all the cells they gained and must start again.", picture_url: "https://en.wikipedia.org/wiki/File:Dead_cells_cover_art.png", release_date: "August 7, 2018", system: "Nintendo Switch", video: "https://www.youtube.com/embed/RvGaSPTcTxc"})

donkey_kong_country = Game.create({name: "Donkey Kong Country: Tropical Freeze", developer: "Retro Studios", genre: "Platformer", description: "Donkey Kong Country: Tropical Freeze is a side-scrolling platformer video game developed by Retro Studios, with assistance from Monster Games, and published by Nintendo for the Wii U. The fifth installment in the main Donkey Kong Country series, Donkey Kong Country: Tropical Freeze is the direct sequel to the 2010 Wii game, Donkey Kong Country Returns, and was released worldwide in February 2014. An enhanced port for the Nintendo Switch was released in May 2018", picture_url: "https://en.wikipedia.org/wiki/File:DKC5_box_art.jpg", release_date: "May 4, 2018", system: "Nintendo Switch", video: "https://www.youtube.com/embed/_5p0SiWHwvw"})

kirby_star_allies = Game.create({name: "Kirby Star Allies", developer: "HAL Laboratory", genre: "Platformer", description: "Kirby Star Allies is a 2.5D platform game played from a side-on perspective. Players control the series' titular protagonist Kirby who can be accompanied by up to three companions. Kirby can throw hearts at enemies to turn them into allies. The game can be played alone with the game's AI controlling companions or cooperatively with other players controlling companions. When Kirby has companions, new special attacks become available which allow Kirby to combine his abilities with those of his allies', a feature not seen since Kirby: Squeak Squad.", picture_url: "https://en.wikipedia.org/wiki/File:Kirby_Star_Allies.jpg", release_date: "March 16,2018", system: "Nintendo Switch", video: "https://www.youtube.com/embed/FNPf9KkL-ik"})


# Game.create({name: "", developer: "", genre: "", description: "", picture_url: "", release_date: system: ""})
#
# Game.create({name: "", developer: "", genre: "", description: "", picture_url: "", release_date: system: ""})



# XBOX ONE GAMES
gears_ofwar_4 = Game.create({name: "Gears of War 4", developer: "The Coalition", genre: "Third-person shooter", description: "Gears of War 4 is a third-person shooter video game developed by The Coalition and published by Microsoft Studios for Microsoft Windows and Xbox One.[2] It is the fourth main installment in the Gears of War series, and the first mainline entry not to be developed by Epic Games. ", picture_url: "https://compass-ssl.xbox.com/assets/84/32/8432a0d9-36a8-48fb-b91c-d0d668106035.jpg?n=GoW4-MWF_GLP-Hero-0_1084x1084.jpg", release_date: "October 11, 2016", system: "Xbox One", video: "https://www.youtube.com/embed/XrfVfRV0zSg"})

halo_5_guardians = Game.create({name: "Halo 5: Guardians", developer: "343 Industries", genre: "	First-person shooter", description: "Halo 5: Guardians is a first-person shooter video game developed by 343 Industries and published by Microsoft Studios for the Xbox One home video game console. The tenth installment and fifth main entry in the Halo series of video games, it was released worldwide on October 27, 2015. ", picture_url: "https://www.windowscentral.com/sites/wpcentral.com/files/styles/xlarge/public/field/image/2015/10/Halo-5-Guardians-main.jpg?itok=v3PVR2C2", release_date: "October 27, 2015", system: "Xbox One", video: "https://www.youtube.com/embed/Rh_NXwqFvHc"})

quantum_break = Game.create({name: "Quantum Break", developer: "Remedy Entertainment", genre: "Action-adventure, third-person shooter", description: "Quantum Break is a science fiction action-adventure third-person shooter video game developed by Remedy Entertainment and published by Microsoft Studios. The game was released worldwide for Microsoft Windows and Xbox One in April 2016. The game centers on Jack Joyce, granted time manipulation powers after a failed time-machine experiment, as he comes into conflict with former friend Paul Serene over how to deal with an apocalyptic End of Time. In addition, the game includes platform game elements in less action-oriented segments. There are also junction points that affect the game's outcome. The game features episodes of an integrated live-action television show, featuring the actors of the characters. The characters interact with the player's choices, displaying the results of the decisions made.", picture_url: "https://en.wikipedia.org/wiki/File:Quantum_Break_cover.jpg", release_date: "April 5, 2016", system: "Xbox One", video: "https://www.youtube.com/embed/KyNYbVPSs38"})

ori_and_the_blind_forest = Game.create({name: "Ori and the Blind Forest", developer: "Moon Studios", genre: "Platform-adventrure,Metroidvania", description: "Ori and the Blind Forest is a platform-adventure Metroidvania video game developed by Moon Studios and published by Microsoft Studios. The game was released for Microsoft Windows and Xbox One on March 2015. In the game, players assume control of Ori, a white guardian spirit, and Sein, the light and eyes of the Forest's Spirit Tree. To progress in the game, players are tasked to move between platforms and solve puzzles. The game features a system called soul links, which allows players to save at will, and an upgrade system that gives players the ability to strengthen Ori's skills. ", picture_url: "https://en.wikipedia.org/wiki/File:Ori_and_the_Blind_Forest_Logo.jpg", release_date: "March 11, 2015", system: "Xbox One", video: "https://www.youtube.com/embed/cklw-Yu3moE"})

sunset_overdrive = Game.create({name: "Sunset Overdrive", developer: "Insomniac Games", genre: "Action-adventure", description: "Sunset Overdrive is an action-adventure third-person shooter video game developed by Insomniac Games and published by Microsoft Studios for the Xbox One and Microsoft Windows. It was announced at Electronic Entertainment Expo 2013, and released worldwide for Xbox One October 2014 and for Microsoft Windows in November 2018. The game is set in 2027, in a fictional metropolis called Sunset City. The player controls an employee of FizzCo, who has to fight off the OD, short for Overcharge Drinkers: humans who have turned into mutants after drinking FizzCo's energy drink beverage. In the dystopian Sunset City the player character can wall-run, use zip-lines, and grind rails to swiftly navigate through it, with a large arsenal of weapons to use. The game also has a cooperative multiplayer mode called Chaos Squad, which tasks players to complete a series of missions with seven players. As the game puts emphasis on momentum, the game does not feature any cover system", picture_url: "https://en.wikipedia.org/wiki/File:Sunset_Overdrive_cover.jpg", release_date: "October 28, 2014", system: "Xbox One", video: "https://www.youtube.com/embed/FqJdZQPBDF0"})

forza_horizon = Game.create({name: "Forza Horizon 4", developer: "Playground Games", genre: "Racing", description: "Forza Horizon 4 is a racing video game set in an open world environment based in a fictional representation of the United Kingdom and features over 450 licensed cars. The game features a route creator which enables players to create their own races.The game takes place in a synchronised shared world, compared to the AI-driven Drivatars from its predecessors, with each server supporting up to 72 players.The game is also playable in offline mode.", picture_url: "https://en.wikipedia.org/wiki/File:Forza_Horizon_4_cover.jpg", release_date: "October 2, 2018", system: "Xbox One", video: "https://www.youtube.com/embed/zJ477xAIlgU"})

player_unknowns_battleground = Game.create({name: "PlayerUnknown's Battlegrounds", developer: "PUGB Corporation", genre: "Battle royale", description: "PlayerUnknown's Battlegrounds (PUBG) is an online multiplayer battle royale game developed and published by PUBG Corporation, a subsidiary of South Korean video game company Bluehole. The game is based on previous mods that were created by Brendan PlayerUnknown Greene for other games using the film Battle Royale for inspiration, and expanded into a standalone game under Greene's creative direction. In the game, up to one hundred players parachute onto an island and scavenge for weapons and equipment to kill others while avoiding getting killed themselves. The available safe area of the game's map decreases in size over time, directing surviving players into tighter areas to force encounters. The last player or team standing wins the round.", picture_url: "https://en.wikipedia.org/wiki/File:PlayerUnknown%27s_Battlegrounds_Steam_Logo.jpg", release_date: "September 4, 2014", system: "Xbox One", video: "https://www.youtube.com/embed/4rG9noTfb4A"})

sea_of_thieves = Game.create({name: "Sea of Thieves", developer: "Rare", genre: "Action-adventure", description: "Sea of Thieves is a pirate-themed action-adventure cooperative multiplayer game played from a first-person perspective.The game features cross-platform play between Windows-based personal computers and Xbox One video game consoles.[4] A group of players travel and explore an open world via a pirate ship and assume different roles such as steering, hoisting sails, navigation, and firing cannons.Players embark on quests, collect loot and engage in combat with other players.Sea of Thieves is a shared game world, which means groups of players will encounter each other regularly throughout their adventures.[3] The game has a cartoonish art style and an exaggerated physics engine that allow players to perform stunts, like being shot out of ship cannons", picture_url: "https://en.wikipedia.org/wiki/File:Sea_of_thieves_cover_art.jpg", release_date: "March 20, 2018", system: "Xbox One", video: "https://www.youtube.com/embed/FqJdZQPBDF0"})

# Game.create({name: "", developer: "", genre: "", description: "", picture_url: "", release_date: "", system: ""})
#
# Game.create({name: "", developer: "", genre: "", description: "", picture_url: "", release_date: "", system: ""})


# WII U GAMES
the_legend_of_zelda = Game.create({name: "The Legend of Zelda: Breath of the Wild", developer: "Nintendo EPD", genre: "Action-adventure", description: "The Legend of Zelda: Breath of the Wild is an action-adventure game developed and published by Nintendo. An entry in the longrunning The Legend of Zelda series, it was released for the Nintendo Switch and Wii U consoles on March 3, 2017. ", picture_url: "https://cdn02.nintendo-europe.com/media/images/10_share_images/games_15/wiiu_14/SI_WiiU_TheLegendOfZeldaBreathOfTheWild.jpg", release_date: "March 3, 2017", system: "Wii U", video: "https://www.youtube.com/embed/1rPxiXXxftE"})

mario_kart_8 = Game.create({name: "Mario Kart 8", developer: "Nintendo EAD", genre: "Kart racing", description: "Mario Kart 8 is a kart racing video game and the eighth major installment in the Mario Kart series, developed and published by Nintendo for their Wii U home video game console. The game was announced at E3 2013 and released worldwide in May 2014.", picture_url: "https://cdn02.nintendo-europe.com/media/images/10_share_images/games_15/wiiu_14/SI_WiiU_MarioKart8_image1600w.jpg" , release_date: "April 28, 2017", system: "Wii U", video:"https://www.youtube.com/embed/tKlRN2YpxRE"})

pikmin_3 = Game.create({name: "Pikmin 3", developer: "Nintendo EAD", genre: "Real-time strategy", description: "Pikmin 3 is a puzzle strategy video game developed and published by Nintendo for the Wii U video game console. It is the sequel to Pikmin 2 (2004) and was first released in Japan on July 13, 2013 and then in all other regions the following month. Game designer Shigeru Miyamoto first announced Pikmin 3 on July 16, 2008 as a game for the Wii console, later stating at E3 2011 that its development had transitioned to Wii U. The game retains the gameplay elements introduced in previous Pikmin games, and adds new features, including new playable characters and Pikmin types, Off-TV Play and downloadable content.", picture_url: "https://en.wikipedia.org/wiki/File:Pikmin_3_box_artwork.png" , release_date: "August 4, 2013", system: "Wii U", video: "https://www.youtube.com/embed/1rPxiXXxftE"})

new_super_mario_bros = Game.create({name: "New Super Mario Bros.U", developer: "Nintendo EAD", genre: "Platform", description: "The game's plot is similar to those of other side-scrolling Mario games. New Super Mario Bros. follows Mario as he fights his way through Bowser's henchmen to rescue Princess Peach. Mario has access to several power-ups that help him complete his quest, including the Super Mushroom, the Fire Flower, and the Starman, each giving him unique abilities. While traveling through eight worlds with a total of 80 levels, Mario must defeat Bowser Jr. and Bowser before finally saving Princess Peach.", picture_url: "https://en.wikipedia.org/wiki/File:New_Super_Mario_Bros._U_box_art.png" , release_date: "May 15, 2006", system: "Wii U", video: "https://www.youtube.com/embed/IQHa4qindfE"})

xenoblade_chronicles_x = Game.create({name: "Xenoblade Chronicles X", developer: "Monolith Soft", genre: "Action-role playing", description: "Xenoblade Chronicles X is an action role-playing video game developed by Monolith Soft and published by Nintendo for the Wii U home video game console in 2015. Xenoblade Chronicles X forms part of the Xeno metaseries, being a spiritual successor to Xenoblade Chronicles without any narrative connections to prior Xeno titles. Carrying over several gameplay elements from Xenoblade Chronicles, players explore the open world planet of Mira, completing a variety of quests and unlocking new regions to explore and gather resources from across Mira's five continents.", picture_url: "https://en.wikipedia.org/wiki/File:Xenoblade_Chronicles_X_-_Boxart.jpg" , release_date: "December 4, 2015", system: "Wii U", video: "https://www.youtube.com/embed/xksPVZptPGM"})

the_wonderful_101 = Game.create({name: "The Wonderful 101", developer: "Platinum Games", genre: "Action-adventure", description: "In The Wonderful 101, players control a horde of superheroes from an isometric viewpoint and can turn them into various objects called Unite Morphs. As levels progress, players must explore each stage to find helpless citizens and recruit them to join their army of heroes. The more heroes gathered, the greater the special morph powers can be. At the cost of depleting their battery meter, players can use "Unite Morph" forms to defeat enemies, solve puzzles, or traverse the environment.", picture_url: "https://en.wikipedia.org/wiki/File:Wonderful_101_box_artwork.jpg" , release_date: "September 15, 2013", system: "Wii U", video: "https://www.youtube.com/embed/z9ueBmNNGus"})

mario_party_10 = Game.create({name: "Mario Party 10", developer: "NDcube", genre: "Party", description: "Mario Party 10[a] is a party video game developed by NDcube and published by Nintendo for their Wii U home video game console. It is the tenth main installment in the Mario Party series, the fourteenth in the franchise, and the first and only game in the series for the Wii U. The game was released worldwide in March 2015. It is the first game in the series since Mario Party 4 to have Donkey Kong as a playable character for every aspect of the game.[b] Mario Party 10 was followed by Super Mario Party for the Nintendo Switch in October 2018.", picture_url: "https://en.wikipedia.org/wiki/File:Mario_Party_10_Small_Official_Boxart.png" , release_date: "March 20, 2015", system: "Wii U", video: "https://www.youtube.com/embed/L69Z39bgdU4"})

splatoon = Game.create({name: "Splatoon", developer: "Nintendo EAD", genre: "Third-person shooter", description: "Splatoon is primarily a team-based third-person shooter which is playable by up to eight players in online four-versus-four matches, although the game also features local one-versus-one multiplayer matches and a single player campaign. Players control characters called Inklings, who have the ability to shapeshift between human and squid forms. In humanoid form, Inklings can shoot ink in their team's color, which can be used to cover the environment or splat opposing players or enemies. Transforming into a squid allows players to swim through the ink of their own color, even up walls and through grates, hiding from the enemy and replenishing their ink supply in the process. Conversely, enemy ink is much slower to move across in humanoid form, cannot be swum through in squid form, and gradually deals damage. Players can use their ink to try and splat their opponents, which will send them back to their team's starting point whilst also providing a large splat of ink.", picture_url: "https://en.wikipedia.org/wiki/File:2717093-spratoonbox.jpg" , release_date: "May 29, 2015", system: "Wii U", video: "https://www.youtube.com/embed/8L54s2m1dPs"})

# Game.create({name: "", developer: "", genre: "", description: "", picture_url: "", release_date: "", system: ""})
#
# Game.create({name: "", developer: "", genre: "", description: "", picture_url: "", release_date: "", system: ""})



# NINTENDO SWITCH GAMES

sonic_mania_plus = Game.create({name: "Sonic Mania", developer: "PagodaWest Games Headcannon", genre: "Platform", description:"Sonic Mania is a 2017 platform game published by Sega for Nintendo Switch, Xbox One, PlayStation 4, and Windows. Produced in commemoration of the Sonic the Hedgehog series' 25th anniversary", picture_url:  "https://nintendowire.com/wp-content/uploads/2018/07/Banner-SonicManiaPlus-Art.jpg", release_date: "August 29, 2017", system: "Nintendo Switch", video: "https://www.youtube.com/embed/LQ1SbHLXlH8"})

bayonetta_2 = Game.create({name: "Bayonetta 2", developer: "PlatinumGames", genre:"Action, hack n slash", description: "Bayonetta 2[a] is an action-adventure hack 'n' slash video game developed by PlatinumGames and published by Nintendo for Wii U[6] and Nintendo Switch", picture_url: "https://cdn02.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_Bayonetta2.jpg", release_date: "February 16, 2018", system: "Nintendo Switch", video: "https://www.youtube.com/embed/-nzBjXXcn7o"})
